services:
  - type: web
    name: flask-fer-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn model:app --timeout 120 --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
    resources:
      cpu: 1x
      memory: 2048